import "./globals.css"

import type { Metadata } from "next"
import { Nunito } from "next/font/google"

import Footer from "./components/footer"
import { Toaster } from "./components/ui/sonner"
import AuthProvider from "./prodivers/auth"

const nunito = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "FSW Barber",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={nunito.className}>
        <AuthProvider>
          {children}
          <Toaster />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  )
}
