import "./globals.css"

import type { Metadata } from "next"
import { Nunito } from "next/font/google"

import AuthProvider from "./_providers/auth"
import Footer from "./components/footer"
import { Toaster } from "./components/ui/sonner"

const nunito = Nunito({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "FSW Barber",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={nunito.className}>
        <AuthProvider>
          <div className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  )
}
